# ATTENTION: when done with setting up this file, you can go into .github/workflows/deploy.yml to use the 'deploy -v' command for this action in order to deploy your lambda

service:
  name: push-notification-lambdas

package:
  individually: true
  exclude:
    - '**/**'

provider:
  name: aws
  runtime: nodejs12.x
  stackName: ${self:service.name}-stack
  stage: ${opt:stage, 'prod'}
  region: eu-central-1
  deploymentBucket:
    name: kaskadi-serverless-deployment-bucket
  stackTags: 
    app: kaskadi
  tags:
    app: kaskadi
    service: ${self:service.name}
    logical-unit: push
    type: eventBridge
functions:
  StocksNotif: ${file(./lambdas/stocks-notif/serverless.yml)}
layers:
  Layer: ${file(./layer/serverless.yml)}
