handler: lambdas/stocks-notif/stocks-notif.handler
name: stocks-notif
layers:
  - { Ref: LayerLambdaLayer }
package:
  include:
    - lambdas/stocks-notif/stocks-notif.js
    - lambdas/stocks-notif/helpers/**
# TODO: add EventBridge as source when the event bus will be properly configured
