name: build
on:
  pull_request:
    branches:
      - 'master'
      - 'dev'
    types: [opened, reopened, edited, synchronize]
    paths:
      - 'layer/**'
      - 'lambdas/**'
      - 'test/**'
      - 'package.json'
env:
  ES_ID: ${{ secrets.ES_ID }}
  ES_SECRET: ${{ secrets.ES_SECRET }}
  ES_ENDPOINT: ${{ secrets.ES_ENDPOINT }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm i
    - name: Test
      run: npm test